### PR TITLE
Fixed quotly.py

### PR DESCRIPTION
**Pull request by successful-fella**
quotly.py wasn't working and there were apparently some bugs.

### CODE REVIEW

**Comment by indianbhaiya** [comment]
Leme chk bro

**Comment by indianbhaiya** [comment]
Reopen

**Comment by indianbhaiya** [comment]
Is it tested by u?

**Comment by successful-fella** [comment]
> Is it tested by u?

Yes. Tested and working fine.

image

**Comment by indianbhaiya** [comment]
Ohk this I m testing now

**Pull request closed without merging**
