### PR TITLE
update telethon to fit dice

### PR DESCRIPTION
**Pull request by RExtafa**

### CODE REVIEW

**Comment by amitkr-codes** [comment]
@mustafairaqi8 It should be to the latest now

**Comment by StarkGang** [comment]
@amitsharma123234 What ?

**Comment by amitkr-codes** [comment]
@StarkGang It's already on the latest version

**Comment by amitkr-codes** [comment]
@mustafairaqi8 Check using .bash pip show telethon

**Comment by RExtafa** [comment]
@amitsharma123234 I tried to Menual deploy yesterday lots of times it is getting locked to 1.10.3.. it is better to remove >= sometimes it won't get the latest for some reason seems like bug in heroku for manual deploy it choses old telethon than latest..but works GOOD WITH in this page deploy and create new app or using .update 

you can keep it like this but just incase to have a more extensive support 
rn i deployed from this page it gets the 1.14 but in manual jumps to 1.10.3 and dice crashes it

**Comment by amitkr-codes** [comment]
@mustafairaqi8 Reset your database and deploy

**Comment by iAkashPattnaik** [comment]
@amitsharma123234 No need

**Comment by indianbhaiya** [comment]
@mustafairaqi8 Yes reset your db and deploy

**Comment by amitkr-codes** [comment]
@BLUE-DEVIL1134 Mine is to the latest with same requirements

**Pull request closed without merging**
