### PR TITLE
New Weather Advance Version Plugin 

### PR DESCRIPTION
**Pull request by StarkGang**

### CODE REVIEW

**Comment by StarkGang** [comment]
@StarkGang @AKASH_AM1 pull it becoz @pureindialover don't have pc R8 now 😐

**Comment by amitkr-codes** [comment]
@StarkGang It can be done by phone also🙄

**Comment by indianbhaiya** [comment]
@amitsharma123234 Be quite till I or Blue Devil pull it

**Comment by Rachit1313** [comment]
Sed

**Pull request merged**
